Fix compilation with SWIG > 4.0
The problem here is the swig director feature together with vectors of
const objects. The dynamic_cast by swig apparently would cast away the
constness, causing a compilation error instead: "error: cannot
'dynamic_cast' 'result' (of type 'std::vector<const
sgpp::optimization::FuzzyInterva l*>::value_type' {aka 'const class
sgpp::optimization::FuzzyInterval*'}) to type 'class Swig::Director*'
(conversion casts away constness)"

I could not find a good workaround for this issue (since it kinda gets
triggered by swig itself within the cast of swig-generated code). So
instead I opted to remove the const from the interface instead (which
still works for the python test/example that uses the
OptFuzzyIntervalVector at least. With that, we can finally use newer
versions of Swig again.